version: '2.2'

services:
  unbound:
    labels:
        com.centurylinklabs.watchtower.enable: "true"
    container_name: unbound.adblock
    image: "mmtnrw/unbound:latest"
    restart: always
    network_mode: host
    privileged: true
    ports: 
      - 53:53
    tty: true
    volumes:
      - "./extra:/extra"
      - "./lists:/lists"
    environment:
       TZ: "Europe/Amsterdam"
       BLACKLIST: "https://winhelp2002.mvps.org/hosts.txt https://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext https://adaway.org/hosts.txt https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts https://mirror1.malwaredomains.com/files/justdomains http://sysctl.org/cameleon/hosts https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list https://raw.githubusercontent.com/superover/TikTok-Blocklist/master/tiktok.txt https://github.com/daylamtayari/Pi-Hole-Blocklist/raw/master/Mirrors/Snapchat-Blocklist--d43m0nhLInt3r.txt"
       WHITELIST: "/lists/whitelist.txt"
#       LISTEN: "127.0.0.1"
