version: '2.2'

services:
  unbound:
    image: "mmtnrw/unbound:latest"
    restart: always
    network_mode: host
    privileged: true
    tty: true
    volumes:
      - "./extra:/extra"
      - "./lists:/lists"
    environment:
       TZ: "Europe/Amsterdam"
       LISTEN: "127.0.0.1"
